### ISSUE TITLE
Taylor Crashes

### ISSUE THREAD

**Issue by quiKsilverItaly** [yopeso/Taylor#35]
When I try to run some taylor commands it crashes. 

For example at the commands `taylor -rc ExcessiveMethodLength=20` or `taylor` following error appears:

> fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file /Users/aculeva/Developer/SourceKitten/Source/SourceKittenFramework/library_wrapper.swift, line 59

Commands like `taylor -v` work, though. 

I use version 0.1.3 and installed it with the .pkg file. Over Homebrew there were also some weird issues.

**Comment by S2dentik** [comment]
@MarcelStructr, for Taylor to run, `Xcode` or  `Command Line Tools OS X for Xcode` have to be installed, have you got them?

**Comment by quiKsilverItaly** [comment]
@S2dentik Yes, i've got Xcode 7.3 installed. If you mean homebrew with command line tools, I also fail using Taylor by installing via homebrew.

I also get a error message by executing this in readme under Source:

> Rebuild dependencies by running carthage bootstrap --platform Mac (Carthage required)
> Clone the project and run make install (latest version of Xcode required).

Do I have to successfully execute this lines first?

**Comment by S2dentik** [comment]
@MarcelStructr What error do you get when trying to install it using Homebrew? Yes, building Taylor by yourself by running the commands would be an option, but if it still doesn't work than you somehow have the Developer folder damaged. `sourcekitd.framework` is normally located at:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
```

Please check if you have it there if building the project from source doesn't help.

**Comment by quiKsilverItaly** [comment]
I just checked `sourcekitd.framework` and the file is there. 

When I try to run taylor by installing via homebrew i get the following error:

> dyld: Library not loaded: @rpath/libclang.dylib
>   Referenced from: /usr/local/Cellar/taylor/0.1.2/Frameworks/TaylorFramework.framework/Versions/A/Frameworks/SourceKittenFramework.framework/SourceKittenFramework
>   Reason: image not found
> Trace/BPT trap: 5

I just installed the Command Line Tools for Xcode 7.3, but nothing changed. 
I realized, that there is already version Xcode 7.3.1 released. Will try it out with that version.

Ah and thanks btw @S2dentik

**Comment by quiKsilverItaly** [comment]
So updated Xcode, but didn't solve the issue. 

Actually the path `/Users/aculeva/Developer/SourceKitten/Source/SourceKittenFramework/library_wrapper.swift` leads to nothing. There is no user named aculeva on my machine. Because of that the program is not working, i guess. How do I change the path?

Edit: Also installed SourceKitten now.

**Comment by S2dentik** [comment]
That misled me first too, but that's just how `SourceKitten` displays the filenames, it takes from the machine it was built on. I've just looked more into their code and it really happens when `sourcekitd.framework` is not at least in one of the `Toolchain` or Xcode `Developer` folder. So what I could say is completely remove Taylor, try to reinstall it, look into a previous version of it and if not I will come with a list of paths where `sourcekitd.framework` should be. Also make sure the process can access those folders, having needed permissions. Alex

**Comment by quiKsilverItaly** [comment]
I tried 0.12, but it also doesn't work. 

I ran `sudo taylor` on 0.13 in the specified directory with the .swift-files and still:

> fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file /Users/aculeva/Developer/SourceKitten/Source/SourceKittenFramework/library_wrapper.swift, line 59

Well, meanwhile I found another program from which I got everything I need. So you don't need to solve this issue for the sake of me, anymore. But if you want to solve the issue nevertheless, I will follow your instructions and inform you then.

**Comment by thelvis4** [comment]
@MarcelStructr We've just released version 0.1.3 to Homebrew. 
Please uninstall taylor `brew uninstall taylor`, update formulae database `brew update`, and install the latest version of taylor `brew install taylor`.
Let me know how it went and if this solves the issue you have.

**Comment by thelvis4** [comment]
@MarcelStructr ping! :)

**Comment by quiKsilverItaly** [comment]
@thelvis4 I will be back on my Mac on Friday. Will leave a reply then (:

**Comment by quiKsilverItaly** [comment]
@thelvis4 Didn't work out today. But will stick on my Mac tomorrow.

**Comment by quiKsilverItaly** [comment]
Sorry for the late response. Still the same problem, when running the command `taylor` in the directory with the code.

> fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file /Users/aculeva/Developer/SourceKitten/Source/SourceKittenFramework/library_wrapper.swift, line 59
> Illegal instruction: 4

I am using Xcode 7.31 right now.

**Comment by S2dentik** [comment]
@MarcelStructr [here](https://github.com/S2dentik/Taylor/tree/updateSourcekitten) is a branch with SourceKitten updated and some logs, in case the files are there but it can't find them. So please:

```
git clone https://github.com/S2dentik/Taylor.git
cd Taylor
git checkout updateSourcekitten
make install
taylor
```

You should see some logs of where SourceKitten is searching for `sourcekit`. If `sourcekit` is there but Taylor skips it and still crashes please check permissions for `sourcekit` inside the folders from logs using `ls -l` and reply.
Thanks

**Comment by thelvis4** [comment]
@MarcelStructr Any news? 🤓

**Comment by quiKsilverItaly** [comment]
@S2dentik @thelvis4 Don't worry, I won't forget this. I use a Mac on my side job, and the last weeks I was not often there. Next week I will leave a reply, though.

**Comment by thelvis4** [comment]
@MarcelStructr Cool! 😎 Looking forward to hearing back from you. 😉

**Comment by quiKsilverItaly** [comment]
So first I deinstalled taylor, and then followed your instructions. When using `make install` I get following:

> make build
> xcodebuild -scheme Taylor -derivedDataPath /Users/envi/tmp/ -configuration Release build
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
> make[1]: **\* [build] Error 1
> make: **\* [install] Error 2

What's that error about? Xcode is installed properly. I looked into the Path `/Library/Developer` and found these: 

> envis-Mac-mini:Developer envi$ ls
> CoreSimulator   XCPGDevices       Xcode

**Comment by thelvis4** [comment]
`xcode-select` developer directory is pointing to `/Library/Developer/CommandLineTools` which doesn't include everything `xcodebuild` command needs. To work correctly, `xcodebuild` needs `xcode-select` developer directory to point to Xcode app directory.
To fix this:
- Make sure you have Xcode installed. Check  if `/Applications/` contains `Xcode.app`. If not, please reinstall Xcode.  
  Not sure why you have `Xcode` directory in `/Library/Developer`. Usually, `Xcode` should be located in `/Applications/` folder while `CommandLineTools` in `/Library/Developer`.
- Point `xcode-select` to the Xcode Developer directory using the following command:
  `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

After this, you can install `taylor` using `make install` or you can install it using `homebrew`. It should work in either case.

Please let us know how it went.

**Comment by quiKsilverItaly** [comment]
Seems to work now after using the command `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` ! 
I get `taylor_report.pmd`generated. Taylor doesn't crash anymore.

Thank you!

**Comment by thelvis4** [comment]
Happy to figure out what the issue was. ☺️ 

Thanks for using `taylor`!💃 😉
